-- Optional event-only seed for testing the event list and admin sheet setup.
-- IDs are generated by PostgreSQL; reruns skip matching title/start-time pairs.

with seed_events as (
  select
    'Test Build Night'::text as title,
    'Synthetic event for checking registration, submissions, and Google Sheets integration.'::text as description,
    'A sample event for testing the full flow.'::text as short_description,
    'Hackathon'::text as category,
    '2026-10-18 18:00:00+05:30'::timestamptz as starts_at,
    '2026-10-19 18:00:00+05:30'::timestamptz as ends_at,
    'Test Innovation Lab'::text as venue,
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1400&q=85'::text as image_url,
    true as is_featured,
    24 as registration_limit,
    true as submissions_open,
    '2026-10-19 15:00:00+05:30'::timestamptz as submission_deadline,
    6 as max_team_size,
    '["Submit a project repository link.", "Include a live demo and a short video pitch."]'::jsonb as submission_rules
  union all
  select
    'Test Design Workshop',
    'Synthetic workshop event for checking event listing and category filters.',
    'A sample workshop for testing the event dashboard.',
    'Workshop',
    '2026-10-22 16:30:00+05:30'::timestamptz,
    '2026-10-22 18:30:00+05:30'::timestamptz,
    'Test Design Studio',
    'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1000&q=85',
    false,
    18,
    false,
    null::timestamptz,
    4,
    '[]'::jsonb
)
insert into public.events (
  title, description, short_description, category, starts_at, ends_at,
  venue, image_url, is_featured, is_active, registration_open,
  registration_limit, submissions_open, submission_deadline, max_team_size,
  submission_rules
)
select
  seed.title,
  seed.description,
  seed.short_description,
  seed.category,
  seed.starts_at,
  seed.ends_at,
  seed.venue,
  seed.image_url,
  seed.is_featured,
  true,
  true,
  seed.registration_limit,
  seed.submissions_open,
  seed.submission_deadline,
  seed.max_team_size,
  seed.submission_rules
from seed_events as seed
where not exists (
  select 1
  from public.events as existing
  where existing.title = seed.title
    and existing.starts_at = seed.starts_at
);
